name: app
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose up -d
      - name: Test
        run: docker run --network appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/
